#!/bin/bash
# Resolve merge conflicts:
# 1. UD (deleted by theirs) → accept deletion
# 2. Driver templates (Драйвер*/Ext/Template.bin) and ParentConfigurations.bin → accept ours
# 3. *.html, Form.xml, Picture.xml, Picture.zip, Picture.png, Picture.svg, Template.xml, Template.txt,
#    Rights.xml, Информация.xml, *.bin, CommonPictures/*.xml → accept theirs
# Remaining conflicts are left for manual resolution.

cd "$(dirname "$0")"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $$: $*"; }
log "start resolve-conflicts.sh"

_count() { [ -n "$1" ] && echo "$1" | grep -c . || echo 0; }

# Counters for summary
declare -A summary
summary[step1_ud]=0; summary[step15_ua]=0; summary[step15_aa]=0
summary[step2_ours]=0; summary[step2_theirs]=0
summary[step3_theirs]=0; summary[step3_manual]=0
summary[fail_checkout]=0; summary[step4_staged]=0

# Retry script for failed checkouts
retry_script="$(dirname "$0")/vendor-retry-failed.sh"
cat > "$retry_script" <<'HEADER'
#!/bin/bash
# Auto-generated by vendor-resolve-conflicts.sh
# Files that failed to resolve via git checkout.
# Run this script to retry resolution.

cd "$(dirname "$0")"
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $$: $*"; }
ok=0; fail=0

resolve() {
    local strategy="$1" f="$2"
    if git checkout "$strategy" -- "$f" 2>/dev/null && git add "$f" 2>/dev/null; then
        if git ls-files -u -- "$f" 2>/dev/null | grep -q .; then
            log "  ✗ still unmerged: $f"
            fail=$((fail + 1))
        else
            log "  ✓ resolved: $f"
            ok=$((ok + 1))
        fi
    else
        log "  ✗ checkout failed: $f"
        fail=$((fail + 1))
    fi
}

HEADER

_batch_checkout() {
    local strategy="$1"; local files="$2"; local step_name="${3:-}"
    [ -z "$files" ] && return
    echo "$files" | tr '\n' '\0' | xargs -0 git checkout "$strategy" -- 2>/dev/null
    echo "$files" | tr '\n' '\0' | xargs -0 git add 2>/dev/null

    # Verify: check that files actually resolved
    local failed=""
    while IFS= read -r f; do
        [ -z "$f" ] && continue
        if git ls-files -u -- "$f" 2>/dev/null | grep -q .; then
            failed+="$f"$'\n'
        fi
    done <<< "$files"

    if [ -n "$failed" ]; then
        local fail_cnt; fail_cnt=$(_count "$failed")
        summary[fail_checkout]=$(( ${summary[fail_checkout]} + fail_cnt ))
        log "  ⚠ $step_name: $fail_cnt file(s) NOT resolved after 'git checkout $strategy':"
        echo "$failed" | head -10 | while IFS= read -r ff; do
            [ -n "$ff" ] && log "    - $ff (status: $(git status --porcelain -- "$ff" 2>/dev/null | cut -c1-2))"
        done
        [ "$fail_cnt" -gt 10 ] && log "    ... and $((fail_cnt - 10)) more"

        # Append to retry script
        while IFS= read -r ff; do
            [ -n "$ff" ] && printf 'resolve "%s" "%s"\n' "$strategy" "$ff" >> "$retry_script"
        done <<< "$failed"
    fi
}

# ─── 1. UD: deleted by theirs ─────────────────────────────────────────────────
log "step 1: Resolving UD (deleted by theirs)"
ud=$(git status --porcelain -- conf/ | grep '^UD ' | sed 's/^UD //')
if [ -n "$ud" ]; then
    echo "$ud" | tr '\n' '\0' | xargs -0 git rm
fi
summary[step1_ud]=$(_count "$ud")
log "  → ${summary[step1_ud]} files resolved (deleted)"

# ─── 1.5. UA: added by theirs (new in theirs) ────────────────────────────────
log "step 1.5: Resolving UA (added by theirs / new in theirs)"
ua=$(git status --porcelain -- conf/ | grep '^UA ' | sed 's/^UA //')
_batch_checkout --theirs "$ua" "step1.5-UA"
summary[step15_ua]=$(_count "$ua")
log "  → ${summary[step15_ua]} files resolved (theirs)"

# ─── 1.6. AA: added by both ──────────────────────────────────────────────────
log "step 1.6: Resolving AA (added by both)"
aa=$(git status --porcelain -- conf/ | grep '^AA ' | sed 's/^AA //')
aa_theirs=""
aa_keep=""
while IFS= read -r f; do
    [ -z "$f" ] && continue
    ours_content=""
    if ours_content="$(git show ":2:$f" 2>/dev/null)"; then
        if printf '%s' "$ours_content" | grep -qF '+кпср' || \
           printf '%s' "$ours_content" | grep -qF 'яя_'; then
            aa_keep+="$f"$'\n'
        else
            aa_theirs+="$f"$'\n'
        fi
    else
        aa_theirs+="$f"$'\n'
    fi
done <<< "$aa"
_batch_checkout --theirs "$aa_theirs" "step1.6-AA"
summary[step15_aa]=$(_count "$aa_theirs")
log "  → $(_count "$aa_theirs") AA resolved (theirs), $(_count "$aa_keep") AA kept (have our markers)"

# ─── 2. UU/AA: batch by mask ──────────────────────────────────────────────────
log "step 2: Resolving UU/AA conflicts"
all=$(git diff --name-only --diff-filter=U -- conf/)

# Ours: Driver templates and ParentConfigurations
ours=$(echo "$all" | grep -E 'conf/CommonTemplates/Драйвер[^/]*/Ext/Template\.bin|conf/Ext/ParentConfigurations\.bin')

# Theirs: known safe masks (drivers and ParentConfigurations excluded via grep -v)
theirs=$(echo "$all" | grep -Ev 'conf/CommonTemplates/Драйвер[^/]*/Ext/Template\.bin|conf/Ext/ParentConfigurations\.bin' | \
    grep -E '\.html$|/Form\.xml$|/Picture\.xml$|/[Pp]icture\.(zip|png|svg)$|/Template\.xml$|/[Tt]emplate\.txt$|/Rights\.xml$|/Информация\.xml$|\.bin$|^conf/CommonPictures/[^/]+\.xml$')

_batch_checkout --ours  "$ours"  "step2-ours"
_batch_checkout --theirs "$theirs" "step2-theirs"

summary[step2_ours]=$(_count "$ours")
summary[step2_theirs]=$(_count "$theirs")
log "  → ${summary[step2_ours]} files resolved (ours), ${summary[step2_theirs]} files resolved (theirs)"

# ─── 3. Remaining (bsl/xml marker guard) ─────────────────────────────────────
log "step 3: Resolving remaining (*.bsl / *.xml) with marker guard"
remaining=$(git diff --name-only --diff-filter=U -- conf/)

if [ -z "$remaining" ]; then
    log "  no remaining conflicts after step 2"
else
    to_theirs=""
    to_keep=""

    total="$(printf '%s\n' "$remaining" | grep -c . || true)"
    processed=0
    start_ts="$(date +%s)"

    while IFS= read -r f; do
        [ -z "$f" ] && continue

        processed=$((processed + 1))
        if [ $((processed % 100)) -eq 0 ]; then
            now_ts="$(date +%s)"
            elapsed=$((now_ts - start_ts))
            if [ "$elapsed" -gt 0 ] && [ "$processed" -gt 0 ]; then
                eta_sec=$(((total - processed) * elapsed / processed))
                [ "$eta_sec" -lt 0 ] && eta_sec=0
            else
                eta_sec=0
            fi
            hh=$((eta_sec / 3600))
            mm=$(((eta_sec % 3600) / 60))
            ss=$((eta_sec % 60))
            log "step 3: processed $processed/$total (*.bsl/*.xml). elapsed=${elapsed}s ETA=$(printf '%02d:%02d:%02d' "$hh" "$mm" "$ss")"
        fi

        case "$f" in
            *.xml|*.bsl)
                # If ours contains marker(s) of our own changes, don't override it.
                ours_content=""
                if ! ours_content="$(git show ":2:$f" 2>/dev/null)"; then
                    # No ours-version to inspect => treat as "markers not present" and take theirs.
                    to_theirs+="$f"$'\n'
                    continue
                fi

                if printf '%s' "$ours_content" | grep -qF '+кпср' || \
                   printf '%s' "$ours_content" | grep -qF 'яя_'; then
                    to_keep+="$f"$'\n'
                else
                    to_theirs+="$f"$'\n'
                fi
                ;;

            *)
                to_keep+="$f"$'\n'
                ;;
        esac
    done <<< "$remaining"

    _batch_checkout --theirs "$to_theirs" "step3-marker"
    summary[step3_theirs]=$(_count "$to_theirs")
    summary[step3_manual]=$(_count "$to_keep")
    log "  → ${summary[step3_theirs]} files resolved (theirs by marker rule), ${summary[step3_manual]} kept for manual"
    log "step 3: marker check done. processed=$processed/$total"
fi

remaining_after=$(git diff --name-only --diff-filter=U -- conf/)
if [ -z "$remaining_after" ]; then
    log "remaining: none (all resolved)"
else
    log "remaining conflicts:\n$remaining_after"
fi

# ─── 4. Stage non-conflict files in conf/ ────────────────────────────────────
log "step 4: Staging non-conflict unstaged files in conf/"
# Files with changes not staged (X=' ', Y=[MADRC]) or untracked (??) in conf/
unstaged=$(git status --porcelain -- conf/ | grep -E '^ [MADRC] |^\?\? ' | sed 's/^...//')
if [ -n "$unstaged" ]; then
    echo "$unstaged" | tr '\n' '\0' | xargs -0 git add 2>/dev/null
fi
summary[step4_staged]=$(_count "$unstaged")
log "  → ${summary[step4_staged]} files staged"

# ─── Summary ─────────────────────────────────────────────────────────────────
remaining_count=$(_count "$remaining_after")
total_resolved=$(( ${summary[step1_ud]} + ${summary[step15_ua]} + ${summary[step15_aa]} \
    + ${summary[step2_ours]} + ${summary[step2_theirs]} \
    + ${summary[step3_theirs]} ))

log "═══════════════════════════════════════════"
log "SUMMARY:"
log "  step 1   UD  (deleted by theirs):  ${summary[step1_ud]}"
log "  step 1.5 UA  (added by theirs):    ${summary[step15_ua]}"
log "  step 1.6 AA  (added by both):      ${summary[step15_aa]}"
log "  step 2   UU  masks (ours):         ${summary[step2_ours]}"
log "  step 2   UU  masks (theirs):       ${summary[step2_theirs]}"
log "  step 3   marker rule (theirs):     ${summary[step3_theirs]}"
log "  step 3   kept for manual:          ${summary[step3_manual]}"
log "  step 4   staged (non-conflict):    ${summary[step4_staged]}"
log "  ─────────────────────────────────────"
log "  TOTAL resolved:                    $total_resolved"
if [ "${summary[fail_checkout]}" -gt 0 ]; then
    log "  ⚠ FAILED to resolve (checkout):   ${summary[fail_checkout]}"
    # Finalize retry script
    cat >> "$retry_script" <<'FOOTER'

log "Done. resolved=$ok, still_failed=$fail"
FOOTER
    chmod +x "$retry_script"
    log "  → Retry script: $retry_script"
else
    # No failures — remove empty retry script
    rm -f "$retry_script"
fi
log "  REMAINING conflicts:               $remaining_count"
log "═══════════════════════════════════════════"

log "end resolve-conflicts.sh"
